[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cairox"
version = "0.1.0"
description = "additional functionality for pycairo"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "Brian Sharland"}]
dependencies = [
    "numpy",
    "Pillow",
]

[tool.setuptools]
packages = ["cairoX"]

[project.urls]
Homepage = "https://github.com/sharland/cairoX"
